/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nilaimahasiswa.view;

/**
 *
 * @author iketu
 */
public class Dashboard extends javax.swing.JFrame {
    
    panelDashboard a = new panelDashboard();
    panelMahasiswa b = new panelMahasiswa();
    panelDosen c = new panelDosen();
    panelMataKuliah d = new panelMataKuliah();
    panelInputNilai f = new panelInputNilai();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        setMinimumSize(new java.awt.Dimension(900, 600));

        // Hapus border scroll
        jScrollWadah.setBorder(null);

        // Viewport ikuti ukuran scroll pane
        jScrollWadah.getViewport().setLayout(new java.awt.BorderLayout());

        // Set panel awal
        jScrollWadah.getViewport().add(a, java.awt.BorderLayout.CENTER);

        jPanelMain.revalidate();
        jPanelMain.repaint();
    }

    public void switchPanel(javax.swing.JPanel panelAktif) {
        // Reset semua panel sebelum pindah
        if (panelAktif instanceof panelMahasiswa) {
            ((panelMahasiswa) panelAktif).clearSelection();
        } else if (panelAktif instanceof panelDosen) {
            ((panelDosen) panelAktif).clearSelection();
        } else if (panelAktif instanceof panelMataKuliah) {
            ((panelMataKuliah) panelAktif).clearSelection();
        } else if (panelAktif instanceof panelInputNilai) {
            ((panelInputNilai) panelAktif).clearSelection();
        } else if (panelAktif instanceof panelDashboard) {
            ((panelDashboard) panelAktif).refresh();
        }

        jScrollWadah.getViewport().removeAll();
        jScrollWadah.getViewport().setLayout(new java.awt.BorderLayout());
        jScrollWadah.getViewport().add(panelAktif, java.awt.BorderLayout.CENTER);
        jPanelMain.revalidate();
        jPanelMain.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelSidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonLogOut = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonDashboard = new javax.swing.JButton();
        jButtonMahasiswa = new javax.swing.JButton();
        jButtonDosen = new javax.swing.JButton();
        jButtonMatkul = new javax.swing.JButton();
        jButtonInputNilai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        jScrollWadah = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelSidebar.setBackground(new java.awt.Color(0, 51, 102));
        jPanelSidebar.setForeground(new java.awt.Color(102, 102, 102));
        jPanelSidebar.setPreferredSize(new java.awt.Dimension(200, 574));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SiNILAI");

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));

        jButtonLogOut.setBackground(new java.awt.Color(204, 0, 51));
        jButtonLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonLogOut.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogOut.setText("Log Out");
        jButtonLogOut.addActionListener(this::jButtonLogOutActionPerformed);

        jButtonDashboard.setText("Dashboard");
        jButtonDashboard.addActionListener(this::jButtonDashboardActionPerformed);

        jButtonMahasiswa.setText("Mahasiswa");
        jButtonMahasiswa.addActionListener(this::jButtonMahasiswaActionPerformed);

        jButtonDosen.setText("Dosen");
        jButtonDosen.addActionListener(this::jButtonDosenActionPerformed);

        jButtonMatkul.setText("Mata Kuliah");
        jButtonMatkul.addActionListener(this::jButtonMatkulActionPerformed);

        jButtonInputNilai.setText("Input Nilai");
        jButtonInputNilai.addActionListener(this::jButtonInputNilaiActionPerformed);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sistem Informasi Nilai");

        javax.swing.GroupLayout jPanelSidebarLayout = new javax.swing.GroupLayout(jPanelSidebar);
        jPanelSidebar.setLayout(jPanelSidebarLayout);
        jPanelSidebarLayout.setHorizontalGroup(
            jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator1)
            .addGroup(jPanelSidebarLayout.createSequentialGroup()
                .addGroup(jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSidebarLayout.createSequentialGroup()
                        .addGroup(jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelSidebarLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelSidebarLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel1))
                            .addGroup(jPanelSidebarLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel2)))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSidebarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDosen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMahasiswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMatkul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonInputNilai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanelSidebarLayout.setVerticalGroup(
            jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSidebarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMahasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonInputNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanelSidebar, java.awt.BorderLayout.WEST);

        jPanelMain.setLayout(new java.awt.BorderLayout());

        jScrollWadah.setBorder(null);
        jPanelMain.add(jScrollWadah, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        // 1. Tampilkan Pop-up Konfirmasi Modern Ala FlatLaf
        int opsi = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "Apakah Anda yakin ingin keluar dari aplikasi?", 
                "Konfirmasi Log Out", 
                javax.swing.JOptionPane.YES_NO_OPTION, 
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        // 2. Jika user memilih tombol YES (Iya)
        if (opsi == javax.swing.JOptionPane.YES_OPTION) {
            // Menutup window Dashboard saat ini
            this.dispose(); 

            // Membuka kembali Form Login
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);

            // Opsional: Memastikan Form Login muncul tepat di tengah layar monitor
            loginForm.setLocationRelativeTo(null); 
        }
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jButtonDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDashboardActionPerformed
        switchPanel(a);
    }//GEN-LAST:event_jButtonDashboardActionPerformed

    private void jButtonMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMahasiswaActionPerformed
        switchPanel(b);
    }//GEN-LAST:event_jButtonMahasiswaActionPerformed

    private void jButtonDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDosenActionPerformed
        switchPanel(c);
    }//GEN-LAST:event_jButtonDosenActionPerformed

    private void jButtonMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatkulActionPerformed
        switchPanel(d);
    }//GEN-LAST:event_jButtonMatkulActionPerformed

    private void jButtonInputNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInputNilaiActionPerformed
        switchPanel(f);
    }//GEN-LAST:event_jButtonInputNilaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDashboard;
    private javax.swing.JButton jButtonDosen;
    private javax.swing.JButton jButtonInputNilai;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonMahasiswa;
    private javax.swing.JButton jButtonMatkul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSidebar;
    private javax.swing.JScrollPane jScrollWadah;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
