/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nilaimahasiswa.view;


import nilaimahasiswa.model.Student;
import nilaimahasiswa.model.Lecturer;
import nilaimahasiswa.model.KRS;
import nilaimahasiswa.model.Course;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author iketu
 */
public class InputNilai extends javax.swing.JFrame {
    
    ArrayList<Student> listMahasiswa = new ArrayList<>();
    ArrayList<Course> listMK = new ArrayList<>();
    final String[] semester = {"1", "2", "3"};
    ArrayList<Lecturer> listLecturer = new ArrayList<>();
    
    final DefaultComboBoxModel comboModelSM = new DefaultComboBoxModel(semester);
    DefaultComboBoxModel<Student> comboModelMhs = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Course> comboModelCourse = new DefaultComboBoxModel<>();
    DefaultComboBoxModel<Lecturer> comboModelLecturer = new DefaultComboBoxModel<>();
    
    Student selectedStudent;
    Course selectedCourse;
    KRS krs;
    Lecturer selectedLecturer;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InputNilai.class.getName());

    /**
     * Creates new form InputNilai
     */
    public InputNilai() {
        initComponents();
        // Memasukkan data Mahasiswa
        listMahasiswa.add(new Student("199000299", "Andi", "001", "Ilmu Komputer"));
        listMahasiswa.add(new Student("19920992", "AGus Jaya", "002", "Ilmu Komputer"));
        listMahasiswa.add(new Student("19912992", "Deni Mudia", "003", "Ilmu Komputer"));
        
        // Memasukkan data Mata Kuliah
        listMK.add(new Course("010", "OOP", 3, 2));
        listMK.add(new Course("011", "English", 3, 2));
        listMK.add(new Course("012", "Web", 3, 2));
        listMK.add(new Course("013", "Mobile", 3, 2));
        
        listLecturer.add(new Lecturer("1001", "Purnamawan", "1020102", "Algoritma"));
        listLecturer.add(new Lecturer("1002", "Agus Seputra", "1020103", "Web"));
        
        // Memasukkan data ke dalam ComboBox Model
        for (Student student : listMahasiswa) {
            comboModelMhs.addElement(student);
        }
        for (Course course : listMK) {
            comboModelCourse.addElement(course);
        }
        for (Lecturer dosen : listLecturer) {
            comboModelLecturer.addElement(dosen);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelKodeSKS = new javax.swing.JLabel();
        jLabelHuruf = new javax.swing.JLabel();
        jComboBoxMK = new javax.swing.JComboBox<>();
        jTextFieldNilaiSikap = new javax.swing.JTextField();
        jTextFieldNilaiUTS = new javax.swing.JTextField();
        jTextFieldNilaiUAS = new javax.swing.JTextField();
        jComboBoxSM = new javax.swing.JComboBox<>();
        jButtonAdd = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxDosen = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelNIM = new javax.swing.JLabel();
        jComboBoxMhs = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNilai = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel1.setText("Identitas Matakuliah");

        jLabel4.setBackground(new java.awt.Color(51, 51, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Form Input Nilai");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 255)));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel6.setText("Matakuliah");

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel2.setText("Kode | SKS");

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel7.setText("Nilai");

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel8.setText("Semester");

        jLabel9.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel9.setText("Nilai Huruf");

        jLabelHuruf.setText("pppp");

        jComboBoxMK.setModel(comboModelCourse);
        jComboBoxMK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxMK.addActionListener(this::jComboBoxMKActionPerformed);

        jTextFieldNilaiSikap.addActionListener(this::jTextFieldNilaiSikapActionPerformed);

        jTextFieldNilaiUTS.addActionListener(this::jTextFieldNilaiUTSActionPerformed);

        jTextFieldNilaiUAS.addActionListener(this::jTextFieldNilaiUASActionPerformed);

        jComboBoxSM.setModel(comboModelSM);
        jComboBoxSM.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxSM.addActionListener(this::jComboBoxSMActionPerformed);

        jButtonAdd.setBackground(new java.awt.Color(0, 204, 204));
        jButtonAdd.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel10.setText("Dosen");

        jComboBoxDosen.setModel(comboModelLecturer);
        jComboBoxDosen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxDosen.addActionListener(this::jComboBoxDosenActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addComponent(jComboBoxMK, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelHuruf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAdd)
                                .addGap(15, 15, 15))
                            .addComponent(jComboBoxSM, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldNilaiSikap, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelKodeSKS, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDosen, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKodeSKS)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldNilaiSikap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelHuruf))
                    .addComponent(jButtonAdd))
                .addGap(16, 16, 16))
        );

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel12.setText("Identitas Mahasiswa");

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 255)));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel3.setText("Nama");

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 12)); // NOI18N
        jLabel5.setText("Nim | Prodi");

        jComboBoxMhs.setModel(comboModelMhs);
        jComboBoxMhs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxMhs.addActionListener(this::jComboBoxMhsActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(68, 68, 68)
                        .addComponent(jComboBoxMhs, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(33, 33, 33)
                        .addComponent(jLabelNIM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMhs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabelNIM))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTableNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "NAMA", "Matakuliah", "SKS", "Dosen", "Nilai"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableNilai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(88, 88, 88))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 993, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 180, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNilaiSikapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNilaiSikapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNilaiSikapActionPerformed

    private void jTextFieldNilaiUTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNilaiUTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNilaiUTSActionPerformed

    private void jTextFieldNilaiUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNilaiUASActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNilaiUASActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        selectedStudent.addKRS(krs);
    
        // Siapkan data untuk baris tabel
        Object[] rowData = {
            selectedStudent.getNim(), 
            selectedStudent.getName(), 
            krs.getCourse().getCourseName(), 
            krs.getCourse().getSKS(), 
            selectedLecturer.getName(),
            krs.getGrade()
        };

        // Masukkan ke jTableNilai (pastikan nama JTable kamu jTableNilai)
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTableNilai.getModel();
        model.addRow(rowData);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jComboBoxMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMhsActionPerformed
        // TODO add your handling code here:
        this.selectedStudent = (Student) jComboBoxMhs.getSelectedItem();
        if(selectedStudent != null) {
            jLabelNIM.setText(selectedStudent.getNim() + " | Prodi: " + selectedStudent.getStudyProgram());
        }
    }//GEN-LAST:event_jComboBoxMhsActionPerformed

    private void jComboBoxMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMKActionPerformed
        // TODO add your handling code here:
        this.selectedCourse = (Course) jComboBoxMK.getSelectedItem();
        if(selectedCourse != null) {
            jLabelKodeSKS.setText(selectedCourse.getCode() + " | SKS: " + Integer.toString(selectedCourse.getSKS()));
        }
    }//GEN-LAST:event_jComboBoxMKActionPerformed

    private void jComboBoxSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSMActionPerformed
        // TODO add your handling code here:
        setKRS(); // Panggil fungsi perhitungan di atas
        jLabelHuruf.setText(krs.getGrade()); // Tampilkan grade ke Label Huruf
    }//GEN-LAST:event_jComboBoxSMActionPerformed

    private void jComboBoxDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDosenActionPerformed
        // TODO add your handling code here:
        this.selectedLecturer = (Lecturer) jComboBoxDosen.getSelectedItem();
    }//GEN-LAST:event_jComboBoxDosenActionPerformed

    private void setKRS() {
        // Ambil nilai dari TextField, pastikan variable name-nya sesuai
        int sikap = Integer.parseInt(jTextFieldNilaiSikap.getText());
        int uts = Integer.parseInt(jTextFieldNilaiUTS.getText());
        int uas = Integer.parseInt(jTextFieldNilaiUAS.getText());

        // Hitung rata-rata
        double rataRata = (uas + uts + sikap) / 3.0;

        // Buat objek KRS baru
        this.krs = new KRS(selectedCourse, rataRata);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InputNilai().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JComboBox<Lecturer> jComboBoxDosen;
    private javax.swing.JComboBox<Course> jComboBoxMK;
    private javax.swing.JComboBox<Student> jComboBoxMhs;
    private javax.swing.JComboBox<String> jComboBoxSM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHuruf;
    private javax.swing.JLabel jLabelKodeSKS;
    private javax.swing.JLabel jLabelNIM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNilai;
    private javax.swing.JTextField jTextFieldNilaiSikap;
    private javax.swing.JTextField jTextFieldNilaiUAS;
    private javax.swing.JTextField jTextFieldNilaiUTS;
    // End of variables declaration//GEN-END:variables
}
