/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nilaimahasiswa.view;

/**
 *
 * @author iketu
 */
public class panelDashboard extends javax.swing.JPanel {

    /**
     * Creates new form panelDashboard
     */
    public panelDashboard() {
        initComponents();
        
        jPanelCardDosen.putClientProperty("FlatLaf.style", "background: #FFFFFF; arc: 20");
        jPanelCardMahasiswa.putClientProperty("FlatLaf.style", "arc: 15");
        jPanelCardMatkul.putClientProperty("FlatLaf.style", "arc: 15");
        jPanelCardKRS.putClientProperty("FlatLaf.style", "arc: 15");
        
        // Mengatur pewarnaan otomatis pada kolom Nilai (kolom indeks ke-3)
        jTableNilaiTerbaru.getColumnModel().getColumn(3).setCellRenderer(new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public java.awt.Component getTableCellRendererComponent(javax.swing.JTable table, Object value, 
                    boolean isSelected, boolean hasFocus, int row, int column) {

                javax.swing.JLabel label = (javax.swing.JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

                // Aktifkan FlatLaf Badge style untuk label di dalam tabel
                label.putClientProperty("component.arc", 8);
                label.setOpaque(true);

                if (value != null) {
                    String nilai = value.toString();
                    if (nilai.equals("A")) {
                        label.setBackground(new java.awt.Color(230, 245, 233)); // Hijau Muda
                        label.setForeground(new java.awt.Color(46, 125, 50));   // Hijau Tua
                    } else if (nilai.equals("B")) {
                        label.setBackground(new java.awt.Color(232, 240, 254)); // Biru Muda
                        label.setForeground(new java.awt.Color(25, 118, 210));  // Biru Tua
                    } else if (nilai.equals("C")) {
                        label.setBackground(new java.awt.Color(255, 243, 224)); // Oranye Muda
                        label.setForeground(new java.awt.Color(230, 81, 0));    // Oranye Tua
                    }
                }
                return label;
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCardDosen = new javax.swing.JPanel();
        jPanelCardDosen.putClientProperty("component.arc", 16);
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanelCardMahasiswa = new javax.swing.JPanel();
        jPanelCardMahasiswa.putClientProperty("component.arc", 16);
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanelCardMatkul = new javax.swing.JPanel();
        jPanelCardMatkul.putClientProperty("component.arc", 16);
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanelCardKRS = new javax.swing.JPanel();
        jPanelCardKRS.putClientProperty("component.arc", 16);
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelTabel = new javax.swing.JPanel();
        jPanelTabel.putClientProperty("component.arc", 16);
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableNilaiTerbaru = new javax.swing.JTable();

        setBackground(new java.awt.Color(245, 245, 245));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCardDosen.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCardDosen.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 0, new java.awt.Color(51, 204, 0)));

        jLabel5.setBackground(new java.awt.Color(234, 234, 234));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(132, 132, 132));
        jLabel5.setText("Total Dosen");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel9.setText("22");

        javax.swing.GroupLayout jPanelCardDosenLayout = new javax.swing.GroupLayout(jPanelCardDosen);
        jPanelCardDosen.setLayout(jPanelCardDosenLayout);
        jPanelCardDosenLayout.setHorizontalGroup(
            jPanelCardDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCardDosenLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelCardDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanelCardDosenLayout.setVerticalGroup(
            jPanelCardDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCardDosenLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        add(jPanelCardDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 150, 110));

        jPanelCardMahasiswa.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCardMahasiswa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 0, new java.awt.Color(51, 204, 255)));

        jLabel4.setBackground(new java.awt.Color(234, 234, 234));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(132, 132, 132));
        jLabel4.setText("Total Mahasiswa");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setText("124");

        javax.swing.GroupLayout jPanelCardMahasiswaLayout = new javax.swing.GroupLayout(jPanelCardMahasiswa);
        jPanelCardMahasiswa.setLayout(jPanelCardMahasiswaLayout);
        jPanelCardMahasiswaLayout.setHorizontalGroup(
            jPanelCardMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCardMahasiswaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelCardMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanelCardMahasiswaLayout.setVerticalGroup(
            jPanelCardMahasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCardMahasiswaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        add(jPanelCardMahasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 150, 110));

        jPanelCardMatkul.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCardMatkul.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 0, new java.awt.Color(255, 204, 51)));

        jLabel6.setBackground(new java.awt.Color(234, 234, 234));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(132, 132, 132));
        jLabel6.setText("Total Mata Kuliah");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setText("16");

        javax.swing.GroupLayout jPanelCardMatkulLayout = new javax.swing.GroupLayout(jPanelCardMatkul);
        jPanelCardMatkul.setLayout(jPanelCardMatkulLayout);
        jPanelCardMatkulLayout.setHorizontalGroup(
            jPanelCardMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCardMatkulLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelCardMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanelCardMatkulLayout.setVerticalGroup(
            jPanelCardMatkulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCardMatkulLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        add(jPanelCardMatkul, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 150, 110));

        jPanelCardKRS.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCardKRS.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 4, 0, 0, new java.awt.Color(153, 0, 153)));

        jLabel7.setBackground(new java.awt.Color(234, 234, 234));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(132, 132, 132));
        jLabel7.setText("Total KRS");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setText("436");

        javax.swing.GroupLayout jPanelCardKRSLayout = new javax.swing.GroupLayout(jPanelCardKRS);
        jPanelCardKRS.setLayout(jPanelCardKRSLayout);
        jPanelCardKRSLayout.setHorizontalGroup(
            jPanelCardKRSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCardKRSLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelCardKRSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanelCardKRSLayout.setVerticalGroup(
            jPanelCardKRSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCardKRSLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        add(jPanelCardKRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 150, 110));

        jLabel1.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        jLabel1.setText("Dashboard");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Selamat datang, Admin!");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanelTabel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Data Nilai Terbaru");

        jTableNilaiTerbaru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Mata Kuliah", "Nilai"
            }
        ));
        jTableNilaiTerbaru.setRowHeight(40);
        jScrollPane3.setViewportView(jTableNilaiTerbaru);

        javax.swing.GroupLayout jPanelTabelLayout = new javax.swing.GroupLayout(jPanelTabel);
        jPanelTabel.setLayout(jPanelTabelLayout);
        jPanelTabelLayout.setHorizontalGroup(
            jPanelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTabelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanelTabelLayout.setVerticalGroup(
            jPanelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTabelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        add(jPanelTabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 670, 480));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelCardDosen;
    private javax.swing.JPanel jPanelCardKRS;
    private javax.swing.JPanel jPanelCardMahasiswa;
    private javax.swing.JPanel jPanelCardMatkul;
    private javax.swing.JPanel jPanelTabel;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableNilaiTerbaru;
    // End of variables declaration//GEN-END:variables
}
